backend:
  name: git-gateway
  branch: main  # Branch where the content is stored

media_folder: "static/img" # Where uploaded images are stored in the repo
public_folder: "/img" # Public URL for images

collections:
  - name: "items"
    label: "Auction Items"
    folder: "content/items"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Gallery", name: "gallery", widget: "list", field: { label: "Image", name: "image", widget: "image" } }
      - { label: "Description", name: "description", widget: "markdown" }
