backend:
  name: git-gateway
  branch: main
  identity_url: https://your-site.netlify.app/.netlify/identity
  role: owner

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "items"
    label: "Auction Items"
    folder: "content/items"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Gallery", name: "gallery", widget: "list", field: { label: "Image", name: "image", widget: "image" } }
      - { label: "Description", name: "description", widget: "markdown" }
